spring:
  application:
    name: hello-dubbo-service-user-provider

user:
  service:
    version: 1.0.0
dubbo:
  provider:
    loadbalance: roundrobin
  scan:
    basePackages: com.hgx.hello.dubbo.service.user.provider.api
  application:
    id: hello-dubbo-service-user-provider
    name: hello-dubbo-service-user-provider
    qos-port: 22222
    qos-enable: true
  protocol:
    id: dubbo
    name: dubbo
    port: 12345
    status: server
    serialization: kryo
  registry:
    id: zookeeper
    address: zookeeper://192.168.124.140:2181?backup=192.168.124.140:2182,192.168.124.140:2183

management:
  endpoint:
    dubbo:
      enabled: true
    dubbo-shutdown:
      enabled: true
    dubbo-configs:
      enabled: true
    dubbo-services:
      enabled: true
    dubbo-references:
      enabled: true
    dubbo-properties:
      enabled: true
  health:
    dubbo:
      status:
        defaults: memory
        extras: load,threadpool
